import { systemWeights } from "react-native-typography";

  export const draftbit_dark = {
    disabledOpacity: 0.5,
    spacing: {
      gutters: 16,
      text: 4,
      small: 8,
      medium: 12,
      large: 16,
    },
    borderRadius: {
      global: 6,
      button: 24,
    } ,
    colors: {
      lightInverse: "rgba(255, 255, 255, 0.68)",
      mediumInverse: "rgba(255, 255, 255, 0.87)",
      strongInverse: "rgba(255, 255, 255, 1)",
      light: "rgba(83, 96, 112, 1)",
      medium: "rgba(154, 163, 177, 1)",
      strong: "rgba(255, 255, 255, 1)",
      divider: "rgba(128, 137, 149, 0.3)",
      error: "rgba(255, 69, 100, 1)",
      background: "rgba(20, 21, 33, 1)",
      surface: "rgba(255, 255, 255, 1)",
      secondary: "rgba(59, 201, 234, 1)",
      primary: "rgba(90, 69, 255, 1)",
    },
    elevation: {
      "0": {
        shadowColor: "rgba(255, 255, 255, 1)",
        shadowOffset: {
          width: 0,
          height: 0,
        },
        shadowRadius: 0,
        shadowOpacity: 0,
        borderWidth: 0,
        borderColor: "rgba(255, 255, 255, 1)",
        borderOpacity: 0,
      },
      "1": {
        shadowColor: "rgba(255, 255, 255, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.06,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 1)",
        borderOpacity: 0.06,
      },
      "2": {
        shadowColor: "rgba(255, 255, 255, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.08,
        borderWidth: 0,
        borderColor: "rgba(255, 255, 255, 1)",
        borderOpacity: 0,
      },
      "3": {
        shadowColor: "rgba(255, 255, 255, 1)",
        shadowOffset: {
          width: 0,
          height: 6,
        },
        shadowRadius: 6,
        shadowOpacity: 0.12,
        borderWidth: 0,
        borderColor: "rgba(255, 255, 255, 1)",
        borderOpacity: 0,
      },
    },
    typography: {
      "headline1": {
        ...systemWeights.bold,
        fontSize: 60,
        letterSpacing: 0,
        lineHeight: 71,
      },
      "headline2": {
        ...systemWeights.bold,
        fontSize: 48,
        letterSpacing: 0,
        lineHeight: 58,
      },
      "headline3": {
        ...systemWeights.bold,
        fontSize: 34,
        letterSpacing: 0,
        lineHeight: 40,
      },
      "headline4": {
        ...systemWeights.bold,
        fontSize: 24,
        letterSpacing: 0,
        lineHeight: 34,
      },
      "headline5": {
        ...systemWeights.bold,
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "headline6": {
        ...systemWeights.bold,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 24,
      },
      "subtitle1": {
        ...systemWeights.regular,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "subtitle2": {
        ...systemWeights.regular,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "body1": {
        ...systemWeights.regular,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "body2": {
        ...systemWeights.regular,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "button": {
        ...systemWeights.bold,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "caption": {
        ...systemWeights.regular,
        fontSize: 12,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "overline": {
        ...systemWeights.regular,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 16,
      },
    },
  };
  export const yummy = {
    disabledOpacity: 0.5,
    spacing: {
      gutters: 16,
      text: 8,
      small: 16,
      medium: 16,
      large: 18,
    },
    borderRadius: {
      global: 6,
      button: 6,
    } ,
    colors: {
      lightInverse: "rgba(255, 255, 255, 0.68)",
      mediumInverse: "rgba(255, 255, 255, 0.87)",
      strongInverse: "rgba(255, 255, 255, 1)",
      light: "rgba(167, 167, 159, 1)",
      medium: "rgba(102, 102, 95, 1)",
      strong: "rgba(33, 9, 63, 1)",
      divider: "rgba(228, 228, 223, 1)",
      error: "rgba(247, 74, 39, 1)",
      background: "rgba(247, 247, 244, 1)",
      surface: "rgba(255, 255, 255, 1)",
      secondary: "rgba(50, 173, 163, 1)",
      primary: "rgba(255, 144, 0, 1)",
    },
    elevation: {
      "0": {
        shadowColor: "rgba(33, 9, 63, 1)",
        shadowOffset: {
          width: 0,
          height: 0,
        },
        shadowRadius: 0,
        shadowOpacity: 0,
        borderWidth: 0,
        borderColor: "rgba(33, 9, 63, 1)",
        borderOpacity: 0,
      },
      "1": {
        shadowColor: "rgba(33, 9, 63, 1)",
        shadowOffset: {
          width: 0,
          height: 3,
        },
        shadowRadius: 5,
        shadowOpacity: 0.16,
        borderWidth: 0,
        borderColor: "rgba(33, 9, 63, 1)",
        borderOpacity: 0,
      },
      "2": {
        shadowColor: "rgba(33, 9, 63, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 3,
        shadowOpacity: 0.1,
        borderWidth: 1,
        borderColor: "rgba(33, 9, 63, 1)",
        borderOpacity: 0.1,
      },
      "3": {
        shadowColor: "rgba(33, 9, 63, 1)",
        shadowOffset: {
          width: 0,
          height: 6,
        },
        shadowRadius: 6,
        shadowOpacity: 0.16,
        borderWidth: 0,
        borderColor: "rgba(33, 9, 63, 1)",
        borderOpacity: 0,
      },
    },
    typography: {
      "caption": {
        fontFamily: "PoppinsBold",
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 20,
      },
      "overline": {
        fontFamily: "PoppinsMedium",
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 16,
      },
      "headline1": {
        fontFamily: "PoppinsBold",
        fontSize: 28,
        letterSpacing: 0,
        lineHeight: 34,
      },
      "headline2": {
        fontFamily: "PoppinsBold",
        fontSize: 24,
        letterSpacing: 0,
        lineHeight: 28,
      },
      "headline3": {
        fontFamily: "PoppinsBold",
        fontSize: 18,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "headline4": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 18,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "headline5": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "headline6": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 20,
      },
      "subtitle1": {
        fontFamily: "PoppinsRegular",
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 18,
      },
      "subtitle2": {
        fontFamily: "PoppinsRegular",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 17,
      },
      "body1": {
        fontFamily: "PoppinsBold",
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 18,
      },
      "body2": {
        fontFamily: "PoppinsBold",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 17,
      },
      "button": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 16,
      },
    },
  };
  export const modern = {
    disabledOpacity: 0.5,
    spacing: {
      gutters: 16,
      text: 4,
      small: 8,
      medium: 12,
      large: 16,
    },
    borderRadius: {
      global: 12,
      button: 8,
    } ,
    colors: {
      lightInverse: "rgba(255, 255, 255, 0.68)",
      mediumInverse: "rgba(255, 255, 255, 0.87)",
      strongInverse: "rgba(255, 255, 255, 1)",
      light: "rgba(165, 173, 183, 1)",
      medium: "rgba(70, 78, 88, 1)",
      strong: "rgba(18, 20, 44, 1)",
      divider: "rgba(234, 237, 242, 1)",
      error: "rgba(255, 69, 100, 1)",
      background: "rgba(251, 252, 253, 1)",
      surface: "rgba(255, 255, 255, 1)",
      secondary: "rgba(59, 201, 234, 1)",
      primary: "rgba(69, 105, 255, 1)",
    },
    elevation: {
      "0": {
        shadowColor: "rgba(18, 20, 44, 1)",
        shadowOffset: {
          width: 0,
          height: 0,
        },
        shadowRadius: 0,
        shadowOpacity: 0,
        borderWidth: 0,
        borderColor: "rgba(18, 20, 44, 1)",
        borderOpacity: 0,
      },
      "1": {
        shadowColor: "rgba(18, 20, 44, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.12,
        borderWidth: 0,
        borderColor: "rgba(18, 20, 44, 1)",
        borderOpacity: 0,
      },
      "2": {
        shadowColor: "rgba(18, 20, 44, 1)",
        shadowOffset: {
          width: 0,
          height: 4,
        },
        shadowRadius: 5,
        shadowOpacity: 0.14,
        borderWidth: 1,
        borderColor: "rgba(18, 20, 44, 1)",
        borderOpacity: 0,
      },
      "3": {
        shadowColor: "rgba(18, 20, 44, 1)",
        shadowOffset: {
          width: 0,
          height: 6,
        },
        shadowRadius: 6,
        shadowOpacity: 0.16,
        borderWidth: 0,
        borderColor: "rgba(18, 20, 44, 1)",
        borderOpacity: 0,
      },
    },
    typography: {
      "headline1": {
        ...systemWeights.bold,
        fontSize: 32,
        letterSpacing: 0,
        lineHeight: 38,
      },
      "headline2": {
        ...systemWeights.bold,
        fontSize: 28,
        letterSpacing: 0,
        lineHeight: 34,
      },
      "headline3": {
        ...systemWeights.bold,
        fontSize: 24,
        letterSpacing: 0,
        lineHeight: 28,
      },
      "headline4": {
        ...systemWeights.bold,
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 24,
      },
      "headline5": {
        ...systemWeights.regular,
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "headline6": {
        ...systemWeights.regular,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 24,
      },
      "subtitle1": {
        ...systemWeights.regular,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "subtitle2": {
        ...systemWeights.regular,
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "body1": {
        ...systemWeights.bold,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "body2": {
        ...systemWeights.bold,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "button": {
        ...systemWeights.bold,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "caption": {
        ...systemWeights.regular,
        fontSize: 12,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "overline": {
        ...systemWeights.regular,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 16,
      },
    },
  };
  export const draftbit = {
    disabledOpacity: 0.5,
    spacing: {
      gutters: 16,
      text: 4,
      small: 8,
      medium: 12,
      large: 16,
    },
    borderRadius: {
      global: 6,
      button: 24,
    } ,
    colors: {
      custom_rgb0_201_25: "rgb(0, 201, 25)",
      custom_rgb201_0_0: "rgb(201, 0, 0)",
      custom_rgb56_201_0: "rgb(56, 201, 0)",
      lightInverse: "rgba(255, 255, 255, 0.68)",
      mediumInverse: "rgba(255, 255, 255, 0.87)",
      strongInverse: "rgba(255, 255, 255, 1)",
      light: "rgba(165, 173, 183, 1)",
      medium: "rgba(70, 78, 88, 1)",
      strong: "rgba(18, 20, 44, 1)",
      divider: "rgba(234, 237, 242, 1)",
      error: "rgba(255, 69, 100, 1)",
      background: "rgba(251, 252, 253, 1)",
      surface: "rgba(255, 255, 255, 1)",
      secondary: "rgba(59, 201, 234, 1)",
      primary: "rgba(90, 69, 255, 1)",
    },
    elevation: {
      "0": {
        shadowColor: "rgba(18, 20, 44, 1)",
        shadowOffset: {
          width: 0,
          height: 0,
        },
        shadowRadius: 0,
        shadowOpacity: 0,
        borderWidth: 0,
        borderColor: "rgba(18, 20, 44, 1)",
        borderOpacity: 0,
      },
      "1": {
        shadowColor: "rgba(18, 20, 44, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.06,
        borderWidth: 1,
        borderColor: "rgba(18, 20, 44, 1)",
        borderOpacity: 0.06,
      },
      "2": {
        shadowColor: "rgba(18, 20, 44, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.08,
        borderWidth: 0,
        borderColor: "rgba(18, 20, 44, 1)",
        borderOpacity: 0,
      },
      "3": {
        shadowColor: "rgba(18, 20, 44, 1)",
        shadowOffset: {
          width: 0,
          height: 6,
        },
        shadowRadius: 6,
        shadowOpacity: 0.12,
        borderWidth: 0,
        borderColor: "rgba(18, 20, 44, 1)",
        borderOpacity: 0,
      },
    },
    typography: {
      "headline1": {
        ...systemWeights.bold,
        fontSize: 60,
        letterSpacing: 0,
        lineHeight: 71,
      },
      "headline2": {
        ...systemWeights.bold,
        fontSize: 48,
        letterSpacing: 0,
        lineHeight: 58,
      },
      "headline3": {
        ...systemWeights.bold,
        fontSize: 34,
        letterSpacing: 0,
        lineHeight: 40,
      },
      "headline4": {
        ...systemWeights.bold,
        fontSize: 24,
        letterSpacing: 0,
        lineHeight: 34,
      },
      "headline5": {
        ...systemWeights.bold,
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "headline6": {
        ...systemWeights.bold,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 24,
      },
      "subtitle1": {
        ...systemWeights.regular,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "subtitle2": {
        ...systemWeights.regular,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "body1": {
        ...systemWeights.regular,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "body2": {
        ...systemWeights.regular,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "button": {
        ...systemWeights.bold,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "caption": {
        ...systemWeights.regular,
        fontSize: 12,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "overline": {
        ...systemWeights.regular,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 16,
      },
    },
  };
  export const fire = {
    disabledOpacity: 0.5,
    spacing: {
      gutters: 16,
      text: 8,
      small: 16,
      medium: 16,
      large: 24,
    },
    borderRadius: {
      global: 8,
      button: 8,
    } ,
    colors: {
      lightInverse: "rgba(255, 255, 255, 0.68)",
      mediumInverse: "rgba(255, 255, 255, 0.87)",
      strongInverse: "rgba(255, 255, 255, 1)",
      light: "rgba(155, 160, 195, 1)",
      medium: "rgba(102, 107, 149, 1)",
      strong: "rgba(27, 33, 75, 1)",
      divider: "rgba(157, 160, 189, 1)",
      error: "rgba(255, 107, 89, 1)",
      background: "rgba(246, 248, 253, 1)",
      surface: "rgba(255, 255, 255, 1)",
      secondary: "rgba(122, 210, 206, 1)",
      primary: "rgba(252, 82, 115, 1)",
    },
    elevation: {
      "0": {
        shadowColor: "rgba(27, 33, 75, 1)",
        shadowOffset: {
          width: 0,
          height: 0,
        },
        shadowRadius: 0,
        shadowOpacity: 0,
        borderWidth: 0,
        borderColor: "rgba(27, 33, 75, 1)",
        borderOpacity: 0,
      },
      "1": {
        shadowColor: "rgba(27, 33, 75, 1)",
        shadowOffset: {
          width: 0,
          height: 4,
        },
        shadowRadius: 6,
        shadowOpacity: 0.06,
        borderWidth: 1,
        borderColor: "rgba(27, 33, 75, 1)",
        borderOpacity: 0.06,
      },
      "2": {
        shadowColor: "rgba(27, 33, 75, 1)",
        shadowOffset: {
          width: 0,
          height: 4,
        },
        shadowRadius: 8,
        shadowOpacity: 0.08,
        borderWidth: 0,
        borderColor: "rgba(27, 33, 75, 1)",
        borderOpacity: 0,
      },
      "3": {
        shadowColor: "rgba(27, 33, 75, 1)",
        shadowOffset: {
          width: 0,
          height: 6,
        },
        shadowRadius: 8,
        shadowOpacity: 0.1,
        borderWidth: 0,
        borderColor: "rgba(27, 33, 75, 1)",
        borderOpacity: 0,
      },
    },
    typography: {
      "headline1": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 60,
        letterSpacing: 0,
        lineHeight: 71,
      },
      "headline2": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 48,
        letterSpacing: 0,
        lineHeight: 58,
      },
      "headline3": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 40,
        letterSpacing: 0,
        lineHeight: 46,
      },
      "headline4": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 24,
        letterSpacing: 0,
        lineHeight: 46,
      },
      "headline5": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "headline6": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 20,
      },
      "subtitle1": {
        fontFamily: "PoppinsRegular",
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "subtitle2": {
        ...systemWeights.regular,
        fontSize: 13,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "body1": {
        fontFamily: "PoppinsRegular",
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "body2": {
        fontFamily: "PoppinsRegular",
        fontSize: 13,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "button": {
        fontFamily: "PoppinsSemiBold",
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "caption": {
        ...systemWeights.regular,
        fontSize: 13,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "overline": {
        fontFamily: "PoppinsMedium",
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 16,
      },
    },
  };
  export const aqua = {
    disabledOpacity: 0.5,
    spacing: {
      gutters: 16,
      text: 4,
      small: 8,
      medium: 12,
      large: 16,
    },
    borderRadius: {
      global: 8,
      button: 8,
    } ,
    colors: {
      lightInverse: "rgba(255, 255, 255, 0.68)",
      mediumInverse: "rgba(255, 255, 255, 0.87)",
      strongInverse: "rgba(0, 22, 60, 1)",
      light: "rgba(153, 190, 226, 1)",
      medium: "rgba(207, 225, 255, 1)",
      strong: "rgba(255, 255, 255, 1)",
      divider: "rgba(67, 101, 162, 0.7)",
      error: "rgba(255, 69, 100, 1)",
      background: "rgba(12, 58, 138, 1)",
      surface: "rgba(61, 106, 184, 1)",
      secondary: "rgba(31, 126, 218, 1)",
      primary: "rgba(37, 163, 217, 1)",
    },
    elevation: {
      "0": {
        shadowColor: "rgba(255, 255, 255, 1)",
        shadowOffset: {
          width: 0,
          height: 0,
        },
        shadowRadius: 0,
        shadowOpacity: 0,
        borderWidth: 0,
        borderColor: "rgba(255, 255, 255, 1)",
        borderOpacity: 0,
      },
      "1": {
        shadowColor: "rgba(255, 255, 255, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.06,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 1)",
        borderOpacity: 0.06,
      },
      "2": {
        shadowColor: "rgba(255, 255, 255, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.08,
        borderWidth: 0,
        borderColor: "rgba(255, 255, 255, 1)",
        borderOpacity: 0,
      },
      "3": {
        shadowColor: "rgba(255, 255, 255, 1)",
        shadowOffset: {
          width: 0,
          height: 6,
        },
        shadowRadius: 6,
        shadowOpacity: 0.12,
        borderWidth: 0,
        borderColor: "rgba(255, 255, 255, 1)",
        borderOpacity: 0,
      },
    },
    typography: {
      "headline1": {
        fontFamily: "NunitoSemiBold",
        fontSize: 34,
        letterSpacing: 0,
        lineHeight: 40,
      },
      "headline2": {
        fontFamily: "NunitoSemiBold",
        fontSize: 30,
        letterSpacing: 0,
        lineHeight: 34,
      },
      "headline3": {
        fontFamily: "NunitoSemiBold",
        fontSize: 28,
        letterSpacing: 0,
        lineHeight: 32,
      },
      "headline4": {
        fontFamily: "NunitoSemiBold",
        fontSize: 24,
        letterSpacing: 0,
        lineHeight: 28,
      },
      "headline5": {
        fontFamily: "NunitoSemiBold",
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "headline6": {
        fontFamily: "NunitoSemiBold",
        fontSize: 18,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "subtitle1": {
        fontFamily: "NunitoRegular",
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "subtitle2": {
        fontFamily: "NunitoRegular",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 18,
      },
      "body1": {
        fontFamily: "NunitoBold",
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 20,
      },
      "body2": {
        fontFamily: "NunitoBold",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 18,
      },
      "button": {
        fontFamily: "NunitoBold",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "caption": {
        ...systemWeights.regular,
        fontSize: 12,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "overline": {
        ...systemWeights.regular,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 16,
      },
    },
  };
  export const organic = {
    disabledOpacity: 0.5,
    spacing: {
      gutters: 16,
      text: 4,
      small: 8,
      medium: 12,
      large: 20,
    },
    borderRadius: {
      global: 6,
      button: 4,
    } ,
    colors: {
      lightInverse: "rgba(255, 255, 255, 0.68)",
      mediumInverse: "rgba(232, 251, 250, 1)",
      strongInverse: "rgba(255, 255, 255, 1)",
      light: "rgba(182, 179, 172, 1)",
      medium: "rgba(127, 124, 115, 1)",
      strong: "rgba(0, 0, 0, 1)",
      divider: "rgba(230, 230, 226, 1)",
      error: "rgba(252, 97, 79, 1)",
      background: "rgba(249, 249, 247, 1)",
      surface: "rgba(255, 255, 255, 1)",
      secondary: "rgba(7, 192, 171, 1)",
      primary: "rgba(107, 192, 62, 1)",
    },
    elevation: {
      "0": {
        shadowColor: "rgba(0, 0, 0, 1)",
        shadowOffset: {
          width: 0,
          height: 0,
        },
        shadowRadius: 0,
        shadowOpacity: 0,
        borderWidth: 0,
        borderColor: "rgba(0, 0, 0, 1)",
        borderOpacity: 0,
      },
      "1": {
        shadowColor: "rgba(127, 124, 115, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.32,
        borderWidth: 0,
        borderColor: "rgba(0, 0, 0, 1)",
        borderOpacity: 0,
      },
      "2": {
        shadowColor: "rgba(127, 124, 115, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.32,
        borderWidth: 0,
        borderColor: "rgba(127, 124, 115, 1)",
        borderOpacity: 0.24,
      },
      "3": {
        shadowColor: "rgba(0, 0, 0, 1)",
        shadowOffset: {
          width: 0,
          height: 6,
        },
        shadowRadius: 6,
        shadowOpacity: 0.12,
        borderWidth: 0,
        borderColor: "rgba(0, 0, 0, 1)",
        borderOpacity: 0,
      },
    },
    typography: {
      "headline1": {
        fontFamily: "MerriweatherRegular",
        fontSize: 60,
        letterSpacing: 0,
        lineHeight: 71,
      },
      "headline2": {
        fontFamily: "MerriweatherRegular",
        fontSize: 48,
        letterSpacing: 0,
        lineHeight: 58,
      },
      "headline3": {
        fontFamily: "MerriweatherRegular",
        fontSize: 34,
        letterSpacing: 0,
        lineHeight: 40,
      },
      "headline4": {
        fontFamily: "MerriweatherRegular",
        fontSize: 24,
        letterSpacing: 0,
        lineHeight: 30,
      },
      "headline5": {
        fontFamily: "MerriweatherRegular",
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 24,
      },
      "headline6": {
        fontFamily: "MerriweatherRegular",
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 20,
      },
      "subtitle1": {
        fontFamily: "WorkSansRegular",
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "subtitle2": {
        fontFamily: "WorkSansRegular",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "body1": {
        fontFamily: "WorkSansMedium",
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "body2": {
        fontFamily: "WorkSansMedium",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "button": {
        fontFamily: "WorkSansSemiBold",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "caption": {
        fontFamily: "WorkSansRegular",
        fontSize: 12,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "overline": {
        fontFamily: "WorkSansMedium",
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 16,
      },
    },
  };
  export const playful = {
    disabledOpacity: 0.5,
    spacing: {
      gutters: 16,
      text: 4,
      small: 8,
      medium: 12,
      large: 20,
    },
    borderRadius: {
      global: 8,
      button: 14,
    } ,
    colors: {
      lightInverse: "rgba(255, 255, 255, 0.68)",
      mediumInverse: "rgba(255, 255, 255, 0.87)",
      strongInverse: "rgba(255, 255, 255, 1)",
      light: "rgba(191, 189, 182, 1)",
      medium: "rgba(123, 121, 114, 1)",
      strong: "rgba(51, 32, 54, 1)",
      divider: "rgba(222, 219, 214, 1)",
      error: "rgba(249, 105, 77, 1)",
      background: "rgba(243, 242, 240, 1)",
      surface: "rgba(255, 255, 255, 1)",
      secondary: "rgba(223, 137, 232, 1)",
      primary: "rgba(125, 78, 245, 1)",
    },
    elevation: {
      "0": {
        shadowColor: "rgba(51, 32, 54, 1)",
        shadowOffset: {
          width: 0,
          height: 0,
        },
        shadowRadius: 0,
        shadowOpacity: 0,
        borderWidth: 0,
        borderColor: "rgba(51, 32, 54, 1)",
        borderOpacity: 0,
      },
      "1": {
        shadowColor: "rgba(51, 32, 54, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.06,
        borderWidth: 1,
        borderColor: "rgba(51, 32, 54, 1)",
        borderOpacity: 0.06,
      },
      "2": {
        shadowColor: "rgba(51, 32, 54, 1)",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowRadius: 4,
        shadowOpacity: 0.08,
        borderWidth: 0,
        borderColor: "rgba(51, 32, 54, 1)",
        borderOpacity: 0,
      },
      "3": {
        shadowColor: "rgba(51, 32, 54, 1)",
        shadowOffset: {
          width: 0,
          height: 6,
        },
        shadowRadius: 6,
        shadowOpacity: 0.12,
        borderWidth: 0,
        borderColor: "rgba(51, 32, 54, 1)",
        borderOpacity: 0,
      },
    },
    typography: {
      "headline1": {
        fontFamily: "RubikMedium",
        fontSize: 60,
        letterSpacing: 0,
        lineHeight: 71,
      },
      "headline2": {
        fontFamily: "RubikMedium",
        fontSize: 48,
        letterSpacing: 0,
        lineHeight: 58,
      },
      "headline3": {
        fontFamily: "RubikMedium",
        fontSize: 34,
        letterSpacing: 0,
        lineHeight: 40,
      },
      "headline4": {
        fontFamily: "RubikMedium",
        fontSize: 24,
        letterSpacing: 0,
        lineHeight: 34,
      },
      "headline5": {
        fontFamily: "RubikMedium",
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "headline6": {
        fontFamily: "RubikMedium",
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 24,
      },
      "subtitle1": {
        fontFamily: "RubikRegular",
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "subtitle2": {
        fontFamily: "RubikRegular",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "body1": {
        fontFamily: "RubikMedium",
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 26,
      },
      "body2": {
        fontFamily: "RubikMedium",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 22,
      },
      "button": {
        fontFamily: "RubikMedium",
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "caption": {
        fontFamily: "RubikRegular",
        fontSize: 12,
        letterSpacing: 0,
        lineHeight: 16,
      },
      "overline": {
        fontFamily: "RubikRegular",
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 16,
      },
    },
  };
